<?php
/**
 * Created by PhpStorm.
 * User: Dmitry
 * Date: 12.07.2018
 * Time: 19:17
 */

class Model_Registration extends Model {

    public function get_data() {

        // Здесь мы просто сэмулируем реальные данные.

        return array(
            "English",
            "Abkhaz",
            "Adyghe",
            "Afrikaans",
            "Akan",
            "Albanian",
            "American Sign Language",
            "Amharic",
            "Arabic",
            "Aragonese",
            "Aramaic",
            "Armenian",
            "Aymara",
            "Balinese",
            "Basque",
            "Betawi",
            "Bosnian",
            "Breton",
            "Bulgarian",
            "Cantonese",
            "Catalan",
            "Cherokee",
            "Chickasaw",
            "Chinese",
            "Coptic",
            "Cornish",
            "Corsican",
            "Crimean Tatar",
            "Croatian",
            "Czech",
            "Danish",
            "Dutch",
            "Esperanto",
            "Estonian",
            "Ewe",
            "Fiji Hindi",
            "Filipino",
            "Finnish",
            "French",
            "Galician",
            "Georgian",
            "German",
            "Greek, Modern",
            "Ancient Greek",
            "Greenlandic",
            "Haitian Creole",
            "Hawaiian",
            "Hindi",
            "Hungarian",
            "Icelandic",
            "Indonesian",
            "Inuktitut",
            "Interlingua",
            "Irish",
            "Italian",
            "Japanese",
            "Javanese",
            "Kabardian",
            "Kalasha",
            "Kannada",
            "Kashubian",
            "Khmer",
            "Kinyarwanda",
            "Korean",
            "Kurdish/Kurdî",
            "Ladin",
            "Latgalian",
            "Latin",
            "Lingala",
            "Livonian",
            "Lojban",
            "Lower Sorbian",
            "Low German",
            "Macedonian",
            "Malay",
            "Malayalam",
            "Mandarin",
            "Manx",
            "Maori",
            "Mauritian Creole",
            "Middle English",
            "Middle Low German",
            "Mongolian",
            "Norwegian",
            "Old Armenian",
            "Old English",
            "Old French",
            "Old Javanese",
            "Old Norse",
            "Old Prussian",
            "Oriya",
            "Pangasinan",
            "Papiamentu",
            "Pashto",
            "Persian",
            "Pitjantjatjara",
            "Polish",
            "Portuguese",
            "Proto-Slavic",
            "Quenya",
            "Rajasthani",
            "Rapa Nui",
            "Romanian",
            "Russian",
            "Sanskrit",
            "Scots",
            "Scottish Gaelic",
            "Serbian",
            "Serbo-Croatian",
            "Slovak",
            "Slovene",
            "Spanish",
            "Sinhalese",
            "Swahili",
            "Swedish",
            "Tagalog",
            "Tajik",
            "Tamil",
            "Tarantino",
            "Telugu",
            "Thai",
            "Tok Pisin",
            "Turkish",
            "Twi",
            "Ukrainian",
            "Upper Sorbian",
            "Urdu",
            "Uyghur",
            "Uzbek",
            "Venetian",
            "Vietnamese",
            "Vilamovian",
            "Volapük",
            "Võro",
            "Welsh",
            "Xhosa",
            "Yiddish",
            "Zazaki",
            "other"
        );
    }
}